### ISSUE TITLE
 Multiple homes not supported yet. Plugin to be extended.

### ISSUE THREAD

**Issue by Micele62** [flod-1/LoxBerry-Plugin-Tibber2MQTT#4]
Hi Florian, ich stelle Preisabweichungen fest, welche ich mir nicht erklären kann. Die Tibber-APP und auch die TibberAPI melden einen aktuellen Preis von 16ct, über tibber2mqtt werden aber 24,7ct gemeldet. Die Differenz beträgt 8,9ct und lässt sich für mich nicht errechnen. AUch ist diese Differenz nicht jede h gleich 8,9ct sondern Different. Habe keine Idee woher die Differenz kommt?
[Tibber Prices.pdf](https://github.com/flod-1/LoxBerry-Plugin-Tibber2MQTT/files/11112399/Tibber.Prices.pdf)

**Comment by flod-1** [comment]
Hallo @Micele62,

hast du das Problem dauerhaft (nur mit teils anderen Abweichungen als die 8,9ct) oder war dies ein einmaliger Effekt? Ersteres würde auf alle Fälle das Debuggen erleichtern.

- Ist dein Vertrag bereits aktiv oder bist du noch vor Vertragsstart?
- Hast du ein oder ggf. mehrere Zu-Hause bei Tibber angelegt?

Kannst du mir bitte - zusätzlich zu den von dir zur Verfügung gestellten Screenshots - einmal über den Loxberry Dateimanager die Datei opt/loxberry/data/plugins/tibber2mqtt/pricecache.json herunterladen und zur Verfügung stellen? Bitte außerdem im Plugin-Manager das Log-Level auf DEBUG stellen und dann die Preise neu abfragen. Dann werden mehr Daten ins Log-File geschrieben, die du im Log-Manager findest. Bitte diese dann ebenfalls einmal zur Verfügung stellen. Achtung: Darin ist teils der Token sichtbar; diesen bitte entsprechend rauslöschen.

Mit diesem vollen Datenset eines Tages, kommen wir dem Problem bei dir hoffentlich auf die Spur und können es zügig lösen.

**Comment by Micele62** [comment]
Ok,gerne.
Das Problem ist dauerhaft. Heute morgen um 07:00 war derPreis tatsächlich gleich und ich dachte es hätte sich erledigt. Aber nun habe ich in der App wieder 30ct und im MQTT 28,4ct, also 2 ct Unterschied. Auch nach erzwungenem Preisupdate bleibt die Differenz, macht ein Problem mit dem Cache etwas unwahrscheinlich.

-  Mein Vertrag ist schon lange aktiv. 
-  Und ja, ich habe testweise ein zweites zuHause angelegt. _Das hat aber keinen Vertrag hinterlegt und liefert innerhalb der TibberApp keine Preise_. Ich weiß, dass das die zuHause-ID innerhalb tibber ändert, dieses Problem hatte ich schon mit den Tibber Witches auf den iPhones. Leider kann man das zweite zuHause nicht selber löschen, wie gesagt, ich hatte es testweise und warte darauf, dass Tibber es wieder löscht. 

Bin gespannt, woran das liegt.
[20230331_093837_410_Process.php.log](https://github.com/flod-1/LoxBerry-Plugin-Tibber2MQTT/files/11119473/20230331_093837_410_Process.php.log)
[20230331_093841_608_Process.php.log](https://github.com/flod-1/LoxBerry-Plugin-Tibber2MQTT/files/11119474/20230331_093841_608_Process.php.log)

**Comment by Micele62** [comment]
Hier noch meine config Einstellungen. Hinweis: Die REl-Preise kommen nicht rüber obwohl angehakt, und der Preis_at kommt mit 0 rüber ?  Sollen nur Hinweise zur Fehlerfindung sein.

<img width="1197" alt="grafik" src="https://user-images.githubusercontent.com/73939110/229067674-2ae6f3e4-4d8e-40de-9c38-cf5757f3a11b.png">

<img width="1193" alt="grafik" src="https://user-images.githubusercontent.com/73939110/229067814-92473a7c-c99c-4baa-8de2-70fc7b536b7b.png">

**Comment by Micele62** [comment]
Das aktuelle log um 13:01 Uhr. Hier stimmen die Preise wieder mit der TibberApp überein.Allerdings landen diese dann nicht im mqtt broker, hier stehen die Werte noch auf dem manuellen Abruf um 12:53 obwohl um 13:01 der stündliche Abruf ohne Fehler erfolgte ...  Vielleicht ein Fehler vom Plugin bei der Weitergabe an den mqtt?

<img width="1179" alt="grafik" src="https://user-images.githubusercontent.com/73939110/229106663-40861468-25cd-4f12-8b39-0a43122ac9c0.png">



[20230331_130101_703_Process.php.log](https://github.com/flod-1/LoxBerry-Plugin-Tibber2MQTT/files/11121163/20230331_130101_703_Process.php.log)

**Comment by flod-1** [comment]
Danke für die Infos!

Kannst du mir bitte noch das LogFile von 12:53 Uhr zur Verfügung stellen?

An für sich sind die von dir beschriebenen Phänomene in der Tat durch das zweite Home erklärbar; das zeigt sowohl die Log-, als auch die Code-Analyse. Mehrere Homes unterstützt das Plugin bisher nicht. 

Das Log um 12:53 wäre interessant, da du dort ja doch Preise in MQTT bekommen hast. Vermutlich hat zu diesem Zeitpunkt die Tibber API die Homes in der anderen Reihenfolge zurückgeliefert.

Ich versuche kurzfristig eine Auswahl des abzufragenden Homes im Plugin zu integrieren.

**Comment by Micele62** [comment]
Hallo Florian, das Log von 12:53 ist leider nicht mehr verfügbar, duch den Neustart um 13:30 wurde es wohl leider gelöscht. Was ich im Moment sehe: Das Log zeigt, dass das Plugin die korrekten Preise abruft (siehe Log um 15:01) aber im MQTT tauchen scheinbar andere auf. _Und momentan ist es so, dass erst gar keine neuen Daten im MQTT auftauchen ( siehe Screenshot)._ Diese sind immer noch von 13:30 Uhr, obwohl um 15:01 und 16:01 abgerufen wurde. Die Daten von 13:30 (manueller Abruf) sind falsch. Im Log von 13:01 ist für 15:00 ein Preis von 0,2587 gelistet, im MQTT steht stand 13:30 aber 0,247. Es sieht so aus, als wären sie nach dem Abruf auf dem Weg zum MQTT verfälscht worden ? Ob das wirklich mit dem zweiten zu Hause zusammenhängt? Zumal zu diesem KEINE Daten ( weil kein Zähler gemeldet) kommen.
<img width="1063" alt="grafik" src="https://user-images.githubusercontent.com/73939110/229146626-8f1c1c77-6705-4554-8708-4248e54ea229.png"> Bild zeigt das MQTT Incoming um 16:21 (!). Die anderen Incomings (ausser tibber) sind zeitaktuell, am MQTT scheint's nicht zu liegen.
[20230331_160101_412_Process.php.log](https://github.com/flod-1/LoxBerry-Plugin-Tibber2MQTT/files/11122825/20230331_160101_412_Process.php.log)
[20230331_133843_187_Process.php.log](https://github.com/flod-1/LoxBerry-Plugin-Tibber2MQTT/files/11122826/20230331_133843_187_Process.php.log)
[20230331_130101_703_Process.php.log](https://github.com/flod-1/LoxBerry-Plugin-Tibber2MQTT/files/11122827/20230331_130101_703_Process.php.log)

**Comment by flod-1** [comment]
@Micele62 Ja, das beschrieben Verhalten hängt zu 100% mit dem zweiten zu Hause bzw. dass dafür keine daten geliefert werden zusammen. Das ist klar nachvollziehbar anhand der zur Verfügung stehender Daten und dem Code. 

Das Plugin erwartet nur einen Preis-Datensatz. Und da der zuerst gelieferte meist der leere ist, sendet es keine neuen Daten an den MQTT Broker.

Wie gesagt unterstützt das Plugin derzeit mehrere zuHause nicht. Ich hoffe die Erweiterung spätestens über das Wochenende fertigstellen zu können.

**Comment by Micele62** [comment]
OK, danke, du hast den Titel ja auch gleich richtig geändert. Danke für's checken und den support. Gruß M.

**Comment by flod-1** [comment]
@Micele62 Das neue Release ist nun verfügbar. Ab v0.3.1 kann ein zuHause ausgewählt werden. Für eine kurze Rückinfo, dass nun wieder alles wie erwartet funktioniert, wäre ich dankbar :)

**Comment by Micele62** [comment]
Hallo Florian, ja, es funktioniert ohne Probleme. Gut gemacht, danke!
